name: Build and Release

on:
  push:
    tags:
      - 'v*' # Trigger on exact versions like v1.2.11

permissions:
  contents: write

jobs:
  release:
    name: Build & Release (${{ matrix.os }})
    runs-on: ${{ matrix.os }}

    strategy:
      max-parallel: 1
      matrix:
        os: [windows-latest, macos-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install

      - name: Build Application Code
        run: npm run build

      - name: Publish Mac
        if: matrix.os == 'macos-latest'
        run: npx electron-builder --mac --x64 --arm64 --publish always
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CSC_IDENTITY_AUTO_DISCOVERY: false
          EP_DRAFT: false

      - name: Build Windows
        if: matrix.os == 'windows-latest'
        run: npx electron-builder --win --publish never
        env:
          CSC_IDENTITY_AUTO_DISCOVERY: false

      - name: Upload Windows Assets
        if: matrix.os == 'windows-latest'
        uses: softprops/action-gh-release@v2
        with:
          files: |
            release/latest.yml
            release/*.exe
            release/*.exe.blockmap
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
