name: Build and Release

on:
  push:
    tags:
      - 'v*' # Trigger on exact versions like v1.2.11

jobs:
  release:
    name: Build & Release (${{ matrix.os }})
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install

      - name: Build Application Code
        run: npm run build

      - name: Publish Mac
        if: matrix.os == 'macos-latest'
        run: npx electron-builder --mac --x64 --arm64 --publish always
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CSC_IDENTITY_AUTO_DISCOVERY: false

      - name: Publish Windows
        if: matrix.os == 'windows-latest'
        run: npx electron-builder --win --publish always
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CSC_IDENTITY_AUTO_DISCOVERY: false
